exports.productsData = [
  {
    stoked: true,
    imgUrl: "imgs/products/f1.jpg",
    name: "Shirt",
    stars: 5,
    price: 100,
  },
  {
    stoked: true,
    imgUrl: "imgs/products/f2.jpg",
    name: "Shirt",
    stars: 5,
    price: 99,
  },
  {
    stoked: true,
    imgUrl: "imgs/products/f3.jpg",
    name: "Shirt",
    stars: 5,
    price: 99,
  },
  {
    stoked: true,
    imgUrl: "imgs/products/f4.jpg",
    name: "Shirt",
    stars: 4,
    price: 90,
  },
  {
    stoked: true,
    imgUrl: "imgs/products/f5.jpg",
    name: "Shirt",
    stars: 4,
    price: 95,
  },
  {
    stoked: false,
    imgUrl: "imgs/products/f6.jpg",
    name: "Shirt",
    stars: 5,
    price: 199,
  },
  {
    stoked: true,
    imgUrl: "imgs/products/f7.jpg",
    name: "Pants",
    stars: 3,
    price: 170,
  },
  {
    stoked: true,
    imgUrl: "imgs/products/f8.jpg",
    name: "Blouse",
    stars: 4,
    price: 90,
  },
  {
    stoked: true,
    imgUrl: "imgs/products/f9.jpg",
    name: "Shirt",
    stars: 4,
    price: 199,
  },
  {
    stoked: true,
    imgUrl: "imgs/products/f10.jpg",
    name: "Shirt",
    stars: 5,
    price: 199,
  },
  {
    stoked: false,
    imgUrl: "imgs/products/f11.jpg",
    name: "Shirt",
    stars: 5,
    price: 149,
  },
  {
    stoked: true,
    imgUrl: "imgs/products/f12.jpg",
    name: "Jacket",
    stars: 5,
    price: 299,
  },

  {
    stoked: true,
    imgUrl: "imgs/products/f14.jpg",
    name: "Long Jacket",
    stars: 5,
    price: 349,
  },

  {
    stoked: true,
    imgUrl: "imgs/products/f6.jpg",
    name: "Shirt",
    stars: 4,
    price: 99,
  },

  {
    stoked: false,
    imgUrl: "imgs/products/f18.jpg",
    name: "Shirt",
    stars: 2,
    price: 70,
  },
  {
    stoked: true,
    imgUrl: "imgs/products/f19.jpg",
    name: "Shirt",
    stars: 4,
    price: 90,
  },
  {
    stoked: true,
    imgUrl: "imgs/products/f20.jpg",
    name: "Shirt",
    stars: 3,
    price: 50,
  },
  {
    stoked: true,
    imgUrl: "imgs/products/f21.jpg",
    name: "Shirt",
    stars: 4,
    price: 90,
  },
  {
    stoked: true,
    imgUrl: "imgs/products/f23.jpg",
    name: "Short",
    stars: 3,
    price: 109,
  },
  {
    stoked: false,
    imgUrl: "imgs/products/f24.jpg",
    name: "T-Shirt",
    stars: 2,
    price: 69,
  },
  {
    stoked: true,
    imgUrl: "imgs/products/f25.jpg",
    name: "T-Shirt",
    stars: 5,
    price: 119,
  },
  {
    stoked: true,
    imgUrl: "imgs/products/f22.jpg",
    name: "Shirt",
    stars: 5,
    price: 149,
  },
  {
    stoked: true,
    imgUrl: "imgs/products/f17.jpg",
    name: "Shirt",
    stars: 5,
    price: 109,
  },
  {
    stoked: false,
    imgUrl: "imgs/products/f15.jpg",
    name: "Shirt",
    stars: 4,
    price: 99,
  },
  {
    stoked: false,
    imgUrl: "imgs/products/f13.jpg",
    name: "Jacket",
    stars: 5,
    price: 399,
  },
  {
    stoked: true,
    imgUrl: "imgs/products/f26.webp",
    name: "Shirt",
    stars: 3,
    price: 200,
  },
  {
    stoked: true,
    imgUrl: "imgs/products/f27.webp",
    name: "Shirt",
    stars: 4,
    price: 230,
  },
  {
    stoked: true,
    imgUrl: "imgs/products/f28.webp",
    name: "Shirt",
    stars: 2,
    price: 210,
  },
  {
    stoked: true,
    imgUrl: "imgs/products/f29.webp",
    name: "Shirt",
    stars: 5,
    price: 250,
  },
  {
    stoked: true,
    imgUrl: "imgs/products/f30.jpg",
    name: "Shirt",
    stars: 3,
    price: 253,
  },
  {
    stoked: true,
    imgUrl: "imgs/products/f31.jpg",
    name: "Shirt",
    stars: 2,
    price: 240,
  },
  {
    stoked: true,
    imgUrl: "imgs/products/f32.jpg",
    name: "Shirt",
    stars: 4,
    price: 260,
  },
  {
    stoked: true,
    imgUrl: "imgs/products/f33.jpg",
    name: "Shirt",
    stars: 5,
    price: 250,
  },
  {
    stoked: true,
    imgUrl: "imgs/products/f34.webp",
    name: "Shirt",
    stars: 4,
    price: 300,
  },
  {
    stoked: true,
    imgUrl: "imgs/products/f35.webp",
    name: "Shirt",
    stars: 4,
    price: 280,
  },
  {
    stoked: true,
    imgUrl: "imgs/products/f36.webp",
    name: "Shirt",
    stars: 5,
    price: 290,
  },
  {
    stoked: true,
    imgUrl: "imgs/products/f38.jpg",
    name: "Shirt",
    stars: 3,
    price: 300,
  },
  {
    stoked: true,
    imgUrl: "imgs/products/f39.webp",
    name: "Shirt",
    stars: 2,
    price: 340,
  },
  {
    stoked: false,
    imgUrl: "imgs/products/f40.jpg",
    name: "Shirt",
    stars: 4,
    price: 200,
  },
  {
    stoked: true,
    imgUrl: "imgs/products/f41.jpg",
    name: "Shirt",
    stars: 3,
    price: 240,
  },
  {
    stoked: true,
    imgUrl: "imgs/products/f43.webp",
    name: "Shirt",
    stars: 5,
    price: 330,
  },
  {
    stoked: true,
    imgUrl: "imgs/products/f44.webp",
    name: "Shirt",
    stars: 1,
    price: 245,
  },
  {
    stoked: true,
    imgUrl: "imgs/products/f45.webp",
    name: "Shirt",
    stars: 2,
    price: 256,
  },
  {
    stoked: false,
    imgUrl: "imgs/products/f46.webp",
    name: "Shirt",
    stars: 4,
    price: 222,
  },
  {
    stoked: true,
    imgUrl: "imgs/products/f47.webp",
    name: "Shirt",
    stars: 3,
    price: 335,
  },
  {
    stoked: true,
    imgUrl: "imgs/products/f48.webp",
    name: "Shirt",
    stars: 5,
    price: 333,
  },

];
