exports.productsData = [
  {
    stoked: true,
    imgSrc: "imgs/products/t-shirts/f1.webp",
    imgs: ["imgs/products/t-shirts/f1/f1.jpg", "imgs/products/t-shirts/f1/f2.jpg", "imgs/products/t-shirts/f1/f3.jpg"],
    name: "T-Shirt",
    stars: 5,
    price: 350,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/t-shirts/f2.webp",
    imgs: ["imgs/products/t-shirts/f2/f1.web", "imgs/products/t-shirts/f2/f2.jpg", "imgs/products/t-shirts/f2/f3.jpg"],
    name: "T-Shirt",
    stars: 4,
    price: 330,
  },
  {
    stoked: false,
    imgSrc: "imgs/products/t-shirts/f3.webp",
    imgs: ["imgs/products/t-shirts/f3/f1.jpg", "imgs/products/t-shirts/f3/f2.jpg", "imgs/products/t-shirts/f3/f3.jpg"],
    name: "T-Shirt",
    stars: 5,
    price: 325,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/t-shirts/f4.webp",
    imgs: ["imgs/products/t-shirts/f4/f1.jpg", "imgs/products/t-shirts/f4/f2.webp", "imgs/products/t-shirts/f4/f3.webp"],
    name: "T-Shirt",
    stars: 3,
    price: 233,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/t-shirts/f5.webp",
    imgs: ["imgs/products/t-shirts/f5/f1.jpg", "imgs/products/t-shirts/f5/f2.jpg", "imgs/products/t-shirts/f5/f3.jpg"],
    name: "T-Shirt",
    stars: 5,
    price: 373,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/t-shirts/f6.webp",
    imgs: ["imgs/products/t-shirts/f6/f1.webp", "imgs/products/t-shirts/f6/f2.jpg", "imgs/products/t-shirts/f6/f3.webp"],
    name: "T-Shirt",
    stars: 2,
    price: 356,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/t-shirts/f7.webp",
    imgs: ["imgs/products/t-shirts/f7/f1.jpg", "imgs/products/t-shirts/f7/f2.jpg", "imgs/products/t-shirts/f7/f3.jpg"],
    name: "T-Shirt",
    stars: 1,
    price: 233,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/t-shirts/f8.webp",
    imgs: ["imgs/products/t-shirts/f8/f1.jpg", "imgs/products/t-shirts/f8/f2.jpg", "imgs/products/t-shirts/f8/f3.jpg"],
    name: "T-Shirt",
    stars: 3,
    price: 245,
  }, {
    stoked: true,
    imgSrc: "imgs/products/polo/f1.webp",
    imgs: ["imgs/products/polo/f1/f1.jpg", "imgs/products/polo/f1/f2.jpg", "imgs/products/polo/f1/f3.jpg"],
    name: "T-Shirt",
    stars: 5,
    price: 350,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/polo/f2.webp",
    iimgs: ["imgs/products/polo/f2/f1.jpg", "imgs/products/polo/f2/f2.jpg", "imgs/products/polo/f2/f3.jpg"],
    name: "T-Shirt",
    stars: 4,
    price: 330,
  },
  {
    stoked: false,
    imgSrc: "imgs/products/polo/f3.webp",
    imgs: ["imgs/products/polo/f3/f1.webp", "imgs/products/polo/f3/f2.jpg", "imgs/products/polo/f3/f3.webp"],
    name: "T-Shirt",
    stars: 5,
    price: 325,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/polo/f4.webp",
    imgs: ["imgs/products/polo/f4/f1.web", "imgs/products/polo/f4/f2.webp", "imgs/products/polo/f4/f3.jpg"],
    name: "T-Shirt",
    stars: 3,
    price: 233,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/polo/f5.webp",
    imgs: ["imgs/products/polo/f5/f1.jpg", "imgs/products/polo/f5/f2.webp", "imgs/products/polo/f5/f3.webp"],
    name: "T-Shirt",
    stars: 5,
    price: 373,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/polo/f6.webp",
    imgs: ["imgs/products/polo/f6/f1.jpg", "imgs/products/polo/f6/f2.jpg", "imgs/products/polo/f6/f3.jpg"],
    name: "T-Shirt",
    stars: 2,
    price: 356,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/polo/f7.webp",
    imgs: ["imgs/products/polo/f7/f1.jpg", "imgs/products/polo/f7/f2.jpg", "imgs/products/polo/f7/f3.webp"],
    name: "T-Shirt",
    stars: 1,
    price: 233,
  },
  {
    stoked: false,
    imgSrc: "imgs/products/polo/f8.webp",
    imgs: ["imgs/products/polo/f8/f1.jpg", "imgs/products/polo/f8/f2.webp", "imgs/products/polo/f8/f3.jpg"],
    name: "T-Shirt",
    stars: 3,
    price: 245,
  },
  {
    stoked: false,
    imgSrc: "imgs/products/f24.jpg", imgs: [],
    name: "T-Shirt",
    stars: 2,
    price: 69,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/f27.webp", imgs: [],
    name: "T-Shirt",
    stars: 4,
    price: 230,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/f28.webp", imgs: [],
    name: "T-Shirt",
    stars: 2,
    price: 210,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/f29.webp", imgs: [],
    name: "T-Shirt",
    stars: 5,
    price: 250,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/f30.jpg", imgs: [],
    name: "T-Shirt",
    stars: 3,
    price: 253,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/f31.jpg", imgs: [],
    name: "T-Shirt",
    stars: 2,
    price: 240,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/f32.jpg", imgs: [],
    name: "T-Shirt",
    stars: 4,
    price: 260,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/f33.jpg", imgs: [],
    name: "T-Shirt",
    stars: 5,
    price: 250,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/f34.webp", imgs: [],
    name: "T-Shirt",
    stars: 4,
    price: 300,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/f35.webp", imgs: [],
    name: "T-Shirt",
    stars: 4,
    price: 280,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/f36.webp", imgs: [],
    name: "T-Shirt",
    stars: 5,
    price: 290,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/f38.jpg", imgs: [],
    name: "T-Shirt",
    stars: 3,
    price: 300,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/f39.webp", imgs: [],
    name: "T-Shirt",
    stars: 2,
    price: 340,
  },
  {
    stoked: false,
    imgSrc: "imgs/products/f40.jpg", imgs: [],
    name: "T-Shirt",
    stars: 4,
    price: 200,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/f41.jpg", imgs: [],
    name: "T-Shirt",
    stars: 3,
    price: 240,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/f43.webp",
    imgs: [],
    name: "T-Shirt",
    stars: 5,
    price: 330,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/f44.webp",
    imgs: [],
    name: "T-Shirt",
    stars: 1,
    price: 245,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/f45.webp", imgs: [],
    name: "T-Shirt",
    stars: 2,
    price: 256,
  },

  {
    stoked: true,
    imgSrc: "imgs/products/shirts/f1.webp",
    imgs: ["imgs/products/shirts/f1/f1.jpg", "imgs/products/shirts/f1/f2.webp", "imgs/products/shirts/f1/f3.jpg"],
    name: "Shirt",
    stars: 5,
    price: 310,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/shirts/f2.webp",
    iimgs: ["imgs/products/shirts/f2/f1.web", "imgs/products/shirts/f2/f2.jpg", "imgs/products/shirts/f2/f3.webp"],
    name: "Shirt",
    stars: 4,
    price: 340,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/shirts/f3.webp",
    imgs: ["imgs/products/shirts/f3/f1.jpg", "imgs/products/shirts/f3/f2.jpg", "imgs/products/shirts/f3/f3.web"],
    name: "Shirt",
    stars: 5,
    price: 325,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/shirts/f4.webp",
    imgs: ["imgs/products/shirts/f4/f1.webp", "imgs/products/shirts/f4/f2.webp", "imgs/products/shirts/f4/f3.jpg"],
    name: "Shirt",
    stars: 3,
    price: 233,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/shirts/f5.webp",
    imgs: ["imgs/products/shirts/f5/f1.jpg", "imgs/products/shirts/f5/f2.jpg", "imgs/products/shirts/f5/f3.jpg"],
    name: "Shirt",
    stars: 5,
    price: 373,
  },
  {
    stoked: false,
    imgSrc: "imgs/products/shirts/f6.webp",
    imgs: ["imgs/products/shirts/f6/f1.webp", "imgs/products/shirts/f6/f2.webp", "imgs/products/shirts/f6/f3.jpg"],
    name: "Shirt",
    stars: 2,
    price: 356,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/shirts/f7.webp",
    imgs: ["imgs/products/shirts/f7/f1.jpg", "imgs/products/shirts/f7/f2.jpg", "imgs/products/shirts/f7/f3.jpg"],
    name: "Shirt",
    stars: 1,
    price: 233,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/shirts/f8.webp",
    imgs: ["imgs/products/shirts/f8/f1.jpg", "imgs/products/shirts/f8/f2.jpg", "imgs/products/shirts/f8/f3.jpg"],
    name: "Shirt",
    stars: 3,
    price: 245,
  },
  {
    stoked: false,
    imgSrc: "imgs/products/f46.webp", imgs: [],
    name: "Shirt",
    stars: 4,
    price: 222,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/f47.webp", imgs: [],
    name: "Shirt",
    stars: 3,
    price: 335,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/f48.webp",
    imgs: [],
    name: "Shirt",
    stars: 5,
    price: 333,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/f26.webp", imgs: [],
    name: "Shirt",
    stars: 3,
    price: 200,
  },

  {
    stoked: true,
    imgSrc: "imgs/products/f1.jpg",
    imgs: [],
    name: "Shirt",
    stars: 5,
    price: 100,
  },

  {
    stoked: true,
    imgSrc: "imgs/products/f2.jpg", imgs: [],
    name: "Shirt",
    stars: 5,
    price: 99,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/f3.jpg", imgs: [],
    name: "Shirt",
    stars: 5,
    price: 99,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/f4.jpg", imgs: [],
    name: "Shirt",
    stars: 4,
    price: 90,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/f5.jpg", imgs: [],
    name: "Shirt",
    stars: 4,
    price: 95,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/f6.jpg", imgs: [],
    name: "Shirt",
    stars: 5,
    price: 199,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/f7.jpg", imgs: [],
    name: "Pants",
    stars: 3,
    price: 170,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/f8.jpg", imgs: [],
    name: "Blouse",
    stars: 4,
    price: 90,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/f9.jpg", imgs: [],
    name: "Shirt",
    stars: 4,
    price: 199,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/f10.jpg", imgs: [],
    name: "Shirt",
    stars: 5,
    price: 199,
  },
  {
    stoked: false,
    imgSrc: "imgs/products/f11.jpg", imgs: [],
    name: "Shirt",
    stars: 5,
    price: 149,
  },
  {
    stoked: false,
    imgSrc: "imgs/products/f18.jpg", imgs: [],
    name: "Shirt",
    stars: 2,
    price: 70,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/f19.jpg", imgs: [],
    name: "Shirt",
    stars: 4,
    price: 90,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/f20.jpg", imgs: [],
    name: "Shirt",
    stars: 3,
    price: 50,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/f21.jpg", imgs: [],
    name: "Shirt",
    stars: 4,
    price: 90,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/f22.jpg", imgs: [],
    name: "Shirt",
    stars: 5,
    price: 149,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/f23.jpg", imgs: [],
    name: "Short",
    stars: 3,
    price: 109,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/f12.jpg", imgs: [],
    name: "Jacket",
    stars: 5,
    price: 299,
  },



  {
    stoked: true,
    imgSrc: "imgs/products/contrast/f1.webp",
    imgs: ["imgs/products/contrast/f1/f1.webp"],
    name: "Contrast",
    stars: 5,
    price: 150,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/contrast/f2.webp",
    iimgs: ["imgs/products/contrast/f2/f1.web"],
    name: "Contrast",
    stars: 4,
    price: 130,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/contrast/f3.webp",
    imgs: ["imgs/products/contrast/f3/f1.webp"],
    name: "Contrast",
    stars: 5,
    price: 125,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/contrast/f4.webp",
    imgs: ["imgs/products/contrast/f4/f1.webp"],
    name: "Contrast",
    stars: 3,
    price: 133,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/contrast/f5.webp",
    imgs: ["imgs/products/contrast/f5/f1.webp"],
    name: "Contrast",
    stars: 5,
    price: 173,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/contrast/f6.webp",
    imgs: ["imgs/products/contrast/f6/f1.webp"],
    name: "Contrast",
    stars: 2,
    price: 156,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/contrast/f3.webp",
    imgs: ["imgs/products/contrast/f3/f1.webp"],
    name: "Contrast",
    stars: 5,
    price: 125,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/contrast/f2.webp",
    iimgs: ["imgs/products/contrast/f2/f1.web"],
    name: "Contrast",
    stars: 4,
    price: 130,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/packs/f1.webp",
    imgs: ["imgs/products/packs/f1/f1.jpg"],
    name: "Packs",
    stars: 5,
    price: 50,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/packs/f2.webp",
    iimgs: ["imgs/products/packs/f2/f1.web"],
    name: "Packs",
    stars: 4,
    price: 30,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/packs/f3.webp",
    imgs: ["imgs/products/packs/f3/f1.webp"],
    name: "Packs",
    stars: 5,
    price: 25,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/packs/f4.webp",
    imgs: ["imgs/products/packs/f4/f1.webp"],
    name: "Packs",
    stars: 3,
    price: 33,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/packs/f5.webp",
    imgs: ["imgs/products/packs/f5/f1.webp"],
    name: "Packs",
    stars: 5,
    price: 73,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/packs/f1.webp",
    imgs: ["imgs/products/packs/f1/f1.jpg"],
    name: "Packs",
    stars: 5,
    price: 50,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/packs/f6.webp",
    imgs: ["imgs/products/packs/f6/f1.webp"],
    name: "Packs",
    stars: 2,
    price: 56,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/packs/f2.webp",
    iimgs: ["imgs/products/packs/f2/f1.web"],
    name: "Packs",
    stars: 4,
    price: 30,
  },

  {
    stoked: true,
    imgSrc: "imgs/products/shoose/f1.webp",
    imgs: ["imgs/products/shoose/f1/f1.jpg", "imgs/products/shoose/f1/f2.webp", "imgs/products/shoose/f1/f3.jpg"],
    name: "Shoose",
    stars: 5,
    price: 350,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/shoose/f2.webp",
    iimgs: ["imgs/products/shoose/f2/f1.webp", "imgs/products/shoose/f2/f2.webp", "imgs/products/shoose/f2/f3.webp"],
    name: "Shoose",
    stars: 4,
    price: 330,
  },
  {
    stoked: false,
    imgSrc: "imgs/products/shoose/f3.webp",
    imgs: ["imgs/products/shoose/f3/f1.webp", "imgs/products/shoose/f3/f2.webp", "imgs/products/shoose/f3/f3.webp"],
    name: "Shoose",
    stars: 5,
    price: 325,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/shoose/f4.webp",
    imgs: ["imgs/products/shoose/f4/f1.jpg", "imgs/products/shoose/f4/f2.webp", "imgs/products/shoose/f4/f3.webp"],
    name: "Shoose",
    stars: 3,
    price: 233,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/shoose/f5.webp",
    imgs: ["imgs/products/shoose/f5/f1.jpg", "imgs/products/shoose/f5/f2.jpg", "imgs/products/shoose/f5/f3.jpg"],
    name: "Shoose",
    stars: 5,
    price: 373,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/shoose/f6.webp",
    imgs: ["imgs/products/shoose/f6/f1.jpg", "imgs/products/shoose/f6/f2.webp", "imgs/products/shoose/f6/f3.webp"],
    name: "Shoose",
    stars: 2,
    price: 356,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/shoose/f7.webp",
    imgs: ["imgs/products/shoose/f7/f1.webp", "imgs/products/shoose/f7/f2.jpg", "imgs/products/shoose/f7/f3.jpg"],
    name: "Shoose",
    stars: 1,
    price: 233,
  },
  {
    stoked: true,
    imgSrc: "imgs/products/shoose/f2.webp",
    iimgs: ["imgs/products/shoose/f2/f1.webp", "imgs/products/shoose/f2/f2.webp", "imgs/products/shoose/f2/f3.webp"],
    name: "Shoose",
    stars: 4,
    price: 330,
  },
];
